In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
a
print(type(a))


<class 'numpy.ndarray'>


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))



[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [14]:
c=np.zeros((2,5),dtype=int)
c

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
c=np.ones((5,2),dtype=int)
c

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [20]:
d=np.eye(3,dtype=bool)
d

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
e=np.full((7,5),8)
e

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [27]:
f=np.arange(1,11,3)
f

array([ 1,  4,  7, 10])

In [34]:
g=np.array([[1,2,3],[4,5,6],[7,8,9]])
h=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(h%g)

[[0 0 1]
 [2 0 4]
 [3 2 1]]


In [38]:
h=np.array([[1,2,3],[4,5,6]])
print(h.ndim)
print(h.shape)
print(h.size)
print(h.dtype)

2
(2, 3)
6
int64


In [42]:
print(g[0:][0:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
z=g.flatten()
z
y=z.reshape(3,3)
print(y.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
print(y.min())
print(y.max())
print(y.mean())
print(y.sum())


1
9
5.0
45


In [56]:
print(y <5)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
print(x.size)


10


array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [72]:
#j=np.random.random(5)
#j 
k=np.random.randint(1,20,5)
k

array([17, 10, 11,  9,  2], dtype=int32)

In [75]:
u=np.array([[1,2,3],[4,5,6],[7,8,9]])
u 
print(np.sum(u,axis=1))

[ 6 15 24]


In [78]:
s=np.eye(5,dtype=int)
s

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
k=np.arange(1,21,2)
k1=np.resize(k,(5,3))
k1


TypeError: reshape() missing 1 required positional argument: 'shape'